### ISSUE TITLE
Array items not being generated

### ISSUE THREAD

**Issue by chyt** [cnizzardini/cakephp-swagger-bake#154]
**Describe the bug**
Schema properties with type `array` require a separate parameter `items` defining the contents of the array. See https://swagger.io/docs/specification/data-models/data-types/#array

When this plugin builds `swagger.json`, the `items` parameter is omitted, resulting in an error in Swagger UI. 

**To Reproduce**
Provide the following schema in `swagger.yml`: 

```
components:
  schemas:
    Filter:
      description: 'Listing filter option'
      type: object
      properties:
        paramNames:
          type: array
          items:
            type: string
```

Observe this output in `swagger.json`

```
    "components": {
        "schemas": {
            "Filter": {
                "description": "Listing filter option",
                "type": "object",
                "properties": {
                    "paramNames": {
                        "type": "array"
                    }
                }
            }
        }
    }
```

In Swagger UI, this results in the following message: `😱 Could not render n, see the console.`

**Expected behavior**
The output should be the following:

```
    "components": {
        "schemas": {
            "Filter": {
                "description": "Listing filter option",
                "type": "object",
                "properties": {
                    "paramNames": {
                        "type": "array",
                        "items": {
                            "type": "string",
                        }
                    }
                }
            }
        }
    }
```

**Version and Platform (please complete the following information):**
 - OS/Platform: Mac
 - CakePHP: 4.1.2
 - SwaggerBake Version: 1.5.1
