### ISSUE TITLE
Components->Schema->Property->Format not being set from YAML

### ISSUE THREAD

**Issue by cnizzardini** [cnizzardini/cakephp-swagger-bake#161]
**Describe the bug**
Components->Schema->Property->Format not being set from YAML

**To Reproduce**
1. Create a YAML schema such as 
```yaml
components:
  schemas:
    Language:
      description: Language Entity
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          format: int64
```
2. Generate OpenAPI

**Expected behavior**

The **`format`** is set for the property.

**Attachments**
If applicable, add screenshots or swagger.json

**Version and Platform (please complete the following information):**
 - CakePHP: 4.0.9
 - SwaggerBake Version: 1.5.3
