### ISSUE TITLE
Add read/write schemas to x-swagger-bake vendor extension

### ISSUE THREAD

**Issue by cnizzardini** [cnizzardini/cakephp-swagger-bake#163]
See: https://swagger.io/docs/specification/openapi-extensions/

Currently, for write operations, a full schema is added to OpenAPI by SwaggerBake. This means SwaggerBake must hold onto a larger array while constructing OpenAPI and it results in a large JSON output. Create write entities in `x-swagger-bake` vendor extension and reference them in operations.

Using the `x-swagger-bake` is a way to reduce the clutter in SwaggerUI and Redoc since vendor extensions are not rendered.

**Example Schema:**

```YAML
x-swagger-bake:
  components:
    schemas:
      Actor-write:
        description: Actor Entity
        type: object
        properties:
          first_name:
            type: string
            minLength: 1
            maxLength: 45
          last_name:
            type: string
            minLength: 1
            maxLength: 45
```

**Example operation**
```YAML
  /actors:
    post:
      operationId: 'actors:add:post'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/x-swagger-bake/components/schemas/Actor-write'
```
