### ISSUE TITLE
Add support for generic collection sample response

### ISSUE THREAD

**Issue by cnizzardini** [cnizzardini/cakephp-swagger-bake#205]
Allow user-defined collection response sample at `#/x-swagger-bake/components/schemas/Generic-Collection`. Example: 

```yaml
x-swagger-bake:
  components:
    schemas:
      # SwaggerBake will read in `Generic-Collection` schema for OpenAPI same responses if defined
      Generic-Collection:
        type: object
        x-data-element: data
        properties:
          collection:
            type: object
            properties:
              url:
                type: string
                format: url
                example: /index
              count:
                type: integer
                example: 20
              total:
                type: integer
                example: 200
              pages:
                type: integer
                example: 10
              next:
                type: string
                format: url
                example: /index?page=:number
              prev:
                type: string
                format: url
                example: /index?page=:number
              first:
                type: string
                format: url
                example: /index
              last:
                type: string
                format: url
                example: /index?page=:number
```
