### ISSUE TITLE
Read, Write, and Edit schemas cause errors when importing schema from YAML

### ISSUE THREAD

**Issue by cnizzardini** [cnizzardini/cakephp-swagger-bake#274]
**Describe the bug**

When using schema defined in YAML, the x-swagger-bake vendor schema READ, WRITE, and EDIT are not created. Swagger reports an error and Redoc fails to load.

**To Reproduce**

Using the demo application add: 

```yaml
    City:
      type: object
      properties:
        id:
          type: integer
          example: 500
        name:
          type: string
          example: /url/path
        country_id:
          type: integer
          example: 1
```

**Expected behavior**

SwaggerUI and Redoc should function as normal.

**Version and Platform (please complete the following information):**
 - OS/Platform: Linux
 - CakePHP: 4.2.*
 - SwaggerBake Version: 1.7.1
