### ISSUE TITLE
Unable to reuse properties definitions as shown in the Open Api Spec.

### ISSUE THREAD

**Issue by declaudefrancois** [cnizzardini/cakephp-swagger-bake#419]
Unability to reuse components Schemas definitions as shown in the [Open Api specification website](https://spec.openapis.org/oas/latest.html#simple-model) (please, follow the link).

I'm getting an `[InvalidArgumentException] Type  is not valid. Must be one of array,boolean,integer,number,object,string in C:\wamp64\www\koxer\vendor\cnizzardini\cakephp-swagger-bake\src\Lib\OpenApi\SchemaTrait.php on line 32` error when trying.

**To Reproduce**
1. Create a simple schema definitions.
2. Try to reuse that schema in another property schema using a ref (a show in the code bellow)
3. Run `bin/cake swagger bake`.

```yml
# ...
    Adress: 
      type: object
      properties:
        city:
          type: string
          example: "Brazzaville"
        zone:
          type: string
          example: "Zone 1"

   User:
     type: object
     properties:
       name:
         type: string
         example: "De claude"
       address:
         $ref: '#components/schemas/Adress'
# ...
```

7. See error: 

```php

      Exception: Type  is not valid. Must be one of array,boolean,integer,number,object,string
  In [{PROJECT_DIR}\vendor\cnizzardini\cakephp-swagger-bake\src\Lib\OpenApi\SchemaTrait.php, line 32]
  
  2022-05-24 18:15:32 error: [InvalidArgumentException] Type  is not valid. Must be one of array,boolean,integer,number,object,string in {PROJECT_DIR}\vendor\cnizzardini\cakephp-swagger-bake\src\Lib\OpenApi\SchemaTrait.php on line 32
  Stack Trace:
  - {PROJECT_DIR}\vendor\cnizzardini\cakephp-swagger-bake\src\Lib\Schema\SchemaPropertyFromYamlFactory.php:27
  - {PROJECT_DIR}\vendor\cnizzardini\cakephp-swagger-bake\src\Lib\Schema\SchemaFromYamlFactory.php:57
  - {PROJECT_DIR}\vendor\cnizzardini\cakephp-swagger-bake\src\Lib\OpenApiFromYaml.php:29
  - {PROJECT_DIR}\vendor\cnizzardini\cakephp-swagger-bake\src\Lib\Swagger.php:41
  - {PROJECT_DIR}\vendor\cnizzardini\cakephp-swagger-bake\src\Lib\SwaggerFactory.php:51
  - {PROJECT_DIR}\vendor\cnizzardini\cakephp-swagger-bake\src\Command\BakeCommand.php:59
  - {PROJECT_DIR}\vendor\cakephp\cakephp\src\Console\BaseCommand.php:179
  - {PROJECT_DIR}\vendor\cakephp\cakephp\src\Console\CommandRunner.php:334
  - {PROJECT_DIR}\vendor\cakephp\cakephp\src\Console\CommandRunner.php:172
  - {PROJECT_DIR}\bin\cake.php:12
```

**Expected behavior**
When running `bin/cake swagger bake` , no error is trown and the resulted User Schema is as follow

```yml
#...
   User:
     type: object
     properties:
       name:
         type: string
         example: "De claude"
       address:
         type: object
         properties:
          city:
            type: string
            example: "Brazzaville"
          zone:
            type: string
            example: "Zone 1"
#...
```

**Attachments**
Screenshot from the [Open Api specification website](https://spec.openapis.org/oas/latest.html#simple-model)
![oas_spec_reusability](https://user-images.githubusercontent.com/81987699/170106251-71403a9a-3411-42f5-bfd0-5554acd7b295.PNG)

**Version and Platform (please complete the following information):**
 - OS/Platform: Windows 10 Version 21H2, build 19044.1706
 - CakePHP: ^4.3
 - SwaggerBake Version: ^2.2

**Comment by cnizzardini** [comment]
Thanks for the report. I'll take a look.

**Comment by cnizzardini** [comment]
Seems like the current release expects a `type`. 

```yaml
        address:
          type: object
          $ref: '#components/schemas/Adress'
```

So you can work around this for now. I will have to see if its possible to not require that to match OpenAPI spec.
