### ISSUE TITLE
Schema type is not being set on query parameters generated from OpenApiSearch

### ISSUE THREAD

**Issue by cnizzardini** [cnizzardini/cakephp-swagger-bake#473]
Example:

```yaml
      parameters:
        - in: query
          name: year
          required: false
          schema:
            description: Value
```

Should have `schema.type` and ideally `schema.format`: 

```yaml
      parameters:
        - in: query
          name: year
          required: false
          schema:
            description: Value
            type: number
            format: year
```
