### ISSUE TITLE
Invalid Enum Syntax

### ISSUE THREAD

**Issue by cnizzardini** [cnizzardini/cakephp-swagger-bake#548]
**Describe the bug**

Enum properties are showing as "Structural error" in swagger editor

**To Reproduce**
Create an enumerated type your database and create a route for it. The enum is produced incorrectly:

```yaml
                  the_model:
                    items:
                      type: object
                      properties:
                        an_enum_property:
                          type: string
                          enum:
                            Value: Value
                            Value2: Value2
```

**Expected behavior**

```yaml
                  the_model:
                    items:
                      type: object
                      properties:
                        an_enum_property:
                          type: string
                          enum:
                            - Value
                            - Value2
```

**Attachments**
If applicable, add screenshots or swagger.json

**Version and Platform (please complete the following information):**
 - OS/Platform: Ubuntu 22
 - CakePHP: 5
 - SwaggerBake Version: 3

**Additional context**

Enums need to be returned after being filtered through `array_values`
